### ISSUE TITLE
Identify Bible API to use

### ISSUE THREAD

**Issue by scottluskcis** [coding-curve/sermon-tree#1]
Identify Bible APIs and determine which would be the best fit for this project.

**Comment by scottluskcis** [comment]
@kshoulde35, I've added this task to document any possible APIs, please provide any comments you may have.

**Comment by scottluskcis** [comment]
I'm not sure which of these are legit, we need to investigate before using any of them:

- API.Bible - https://scripture.api.bible/
- Bible.org API - https://www.programmableweb.com/api/bibleorg
- GetBible.NET - https://getbible.net/api
- NET Bible Web Service - https://labs.bible.org/api_web_service
- Faithlife - https://developer.faithlife.com/
- YouVersion APIs - https://yv-public-api-docs.netlify.app/getting-started.html
- Biblia API - https://bibliaapi.com/docs/

**Comment by scottluskcis** [comment]
@kshoulde35, what are your thoughts on this one?

**Comment by kshoulde35** [comment]
@scottluskcis I am in the process of reviewing your list. Prior to seeing your list I went to the Biblia API because from what I understand it's what Faithlife uses. Faithlife is a household name in Seminaries and in churches because of their Logos product. It is arguably the best Bible Study tool out there right now. This would lead me to believe that whatever API they are using is going to be pretty robust. 

We can set up a demo end of the week and I can show you what their web app looks like. Logos started out as a desktop-only deal but a couple of years ago they made a web version you could use because all of the books and resources that you download with the program itself take up a lot of space.
